### ISSUE TITLE
Docs: Functions with multiple outputs cannot be called explicitly

### ISSUE THREAD

**Issue by madhur-tandon** [square/bionic#248]
In the documentation here: https://bionic.readthedocs.io/en/stable/concepts.html#defining-multiple-outputs-using-decorators, it should be mentioned that functions which contain multiple outputs (i.e. which use `@bn.outputs`) such as `split_name` cannot be called explicitly i.e. `flow.get.split_name()` is not allowed. If one does this, it leads to an error: `bionic.exception.UndefinedEntityError: "Entity 'split_name' is not defined"`. A consequence of this is that such functions cannot be at the end of the pipeline (they cannot be terminal functions), they need to be intermediate ones in the pipeline.

**Comment by namanjain** [comment]
The entity name and the function name are the same when you don't use the `outputs` decorator. This might give one the impression that the `get` APIs computes and gets the function's value, but it is actually the entity's value. If you look at `Flow.get` documentation, you will see that the API's name field is "The name of an entity" and returns " the value of the entity".

Basically, Bionic APIs deal with entities instead of functions. If you look at the rendered DAG for your flow, you would also notice that the DAG won't have a `split_name` node, but it will have the `first_name` and `last_name` nodes since they are your entities.

**Comment by madhur-tandon** [comment]
Thanks @namanjain! Closing the issue.
